general.import = [
  "~/.config/alacritty/nord.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "CommitMono Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "CommitMono Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "CommitMono Nerd Font Propo"
style = "Italic"

[font.normal]
family = "CommitMono Nerd Font Propo"
style = "Regular"

[window]
padding = {x=3,y=3}
opacity = 0.95
