[tasks]
image_bound = [65535, 65535]

[mgr]
show_hidden = false

[opener]
edit = [
	{ run = '/usr/bin/nvim "$@"', block = true, for = 'linux' }
]

open_pdf = [
	 { run = '/usr/bin/okular "$@"', block = false, orphan = true, for = 'linux' }
]

[open]
prepend_rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "application/pdf", use = "open_pdf" },
	{ mime = "application/*", use = "edit" },
]
